// AUTO-GENERATED by scripts/codegen.mjs — do not edit
export const ADDR = {
    chainId: 91342,
    mockKRW: "0x44FAb686723C7672CF7cA9018baf502AFfE55d04",
    mockDojang: "0x850Eb31fd5418e902B8DB1e7f126b12032F787aB",
    factory: "0xb5b8f10fE64A785279329e1Ab1fE4AE67F3975A7",
    poolFactory: "0x392C0Dbb43d3f118D10f80F7FE33E5aeba41F7f6",
    dojangEASAdapter: "0x69903dD3b32B5EC3BB8DE8D167053ec80e4b3566",
    offeringA: "0xdE5c071C58553A9fd8662eDdD51A30bAFCfabaec",
    offeringB: "0x1e5050B8f6e6A5203dab37902b051B421D76b32c",
} as const;
// Approx. block of the current deployment — event scans start here (GIWA caps
// eth_getLogs at 100k blocks per request, so scans are chunked from this base).
export const DEPLOY_BLOCK = 31443000n;
