// Generates web/src/contracts/{abis.ts,addresses.ts} from the repo's forge
// artifacts (out/) and deployment records (deployments/). Run via `npm run codegen`.
import {readFileSync, writeFileSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {dirname, join} from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const CONTRACTS = [
    "MapaeFactory",
    "Offering",
    "MembershipToken",
    "MockKRW",
    "MockDojang",
    "RedeemManager",
    "Sponsorship",
    "MapaePool",
];

let abis = "// AUTO-GENERATED by scripts/codegen.mjs — do not edit\n";
for (const name of CONTRACTS) {
    const art = JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8"));
    abis += `export const ${name}Abi = ${JSON.stringify(art.abi)} as const;\n`;
}
writeFileSync(join(root, "web", "src", "contracts", "abis.ts"), abis);

const dep = JSON.parse(readFileSync(join(root, "deployments", "giwa-sepolia.json"), "utf8"));
const demo = JSON.parse(readFileSync(join(root, "deployments", "demo-state.json"), "utf8"));
const addresses = `// AUTO-GENERATED by scripts/codegen.mjs — do not edit
export const ADDR = {
    chainId: ${dep.chainId},
    mockKRW: "${dep.mockKRW}",
    mockDojang: "${dep.mockDojang}",
    factory: "${dep.factoryMock}",
    poolFactory: "${dep.poolFactory}",
    dojangEASAdapter: "${dep.dojangEASAdapter}",
    offeringA: "${demo.offeringA}",
    offeringB: "${demo.offeringB}",
} as const;
// Approx. block of the current deployment — event scans start here (GIWA caps
// eth_getLogs at 100k blocks per request, so scans are chunked from this base).
export const DEPLOY_BLOCK = 31443000n;
`;
writeFileSync(join(root, "web", "src", "contracts", "addresses.ts"), addresses);
console.log("codegen: abis.ts + addresses.ts written");
